# default.yml
# faultline service name
serviceName: faultline
# AWS deploy region
region: ap-northeast-1
# S3 bucket name
s3BucketName: (EDITME)
# Dynamodb table prefix
dynamodbTablePrefix: faultline
# Error tracking count interval (year / month / day / hour / minute)
timeunit: minute
# faultline API Key for full control (!This is not API Gateway API Key!)
masterApiKey: (EDITME)
# faultline API Key for POST errors only (!This is not API Gateway API Key!)
clientApiKey: (EDITME)
# faultline error data Retention (days / -1 is unlimited)
errorDataRetentionInDays: -1
# faultline functions CloudWatchLogs Retention (days / -1 is unlimited)
logRetentionInDays: 180
# Use AWS KMS Key to encrypt POST params (notifications)
useKms: false
# AWS KMS Key alias
kmsKeyAlias: faultline
