service: faultline

frameworkVersion: ">=1.17.0 <2.0.0"

provider:
  name: aws
  environment: ${file(src/lib/env.js):env}
  runtime: nodejs6.10
  stage: v0
  region: ${self:provider.environment.FAULTLINE_REGION}
  timeout: 10
  cfLogs: true
  apiKey: false
  iamRoleStatements:
    - Effect: Allow
      Resource:
        - { "Fn::Join" : ["", ["arn:aws:dynamodb:", "${self:provider.environment.FAULTLINE_REGION}", ":*:*" ] ] }
      Action:
        - "dynamodb:*"
    - Effect: Allow
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:DeleteObject"
      Resource:
        - { "Fn::Join" : ["", ["arn:aws:s3:::", "${self:provider.environment.FAULTLINE_S3_BUCKET_NAME}"] ] }
        - Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - ${self:provider.environment.FAULTLINE_S3_BUCKET_NAME}
            - "/*"
    - Effect: Allow
      Action:
        - "lambda:InvokeFunction"
        - "lambda:InvokeAsync"
      Resource:
        - "arn:aws:lambda:${self:provider.environment.FAULTLINE_REGION}:*:function:faultline-${self:provider.stage}-callNotifications"
    - Effect: Allow
      Action:
        - "kms:Encrypt"
        - "kms:Decrypt"
        - "kms:ListAliases"
      Resource:
        - "*"

package:
  include:
    - serverless.yml
    - src/**
  exclude:
    - .git/**
    - doc/**
    - node_modules/aws-sdk/**

functions:
  projectsList:
    handler: src/handlers/projects/get.list
    events:
      - http:
          path: projects
          method: get
          cors: true
          integration: lambda-proxy
  projectsDelete:
    handler: src/handlers/projects/delete.delete
    timeout: 30
    events:
      - http:
          path: projects/{project}
          method: delete
          cors: true
          integration: lambda-proxy
  errorsPost:
    handler: src/handlers/errors/post.post
    events:
      - http:
          path: projects/{project}/errors
          method: post
          integration: lambda-proxy
  errorsList:
    handler: src/handlers/errors/get.list
    events:
      - http:
          path: projects/{project}/errors
          method: get
          cors: true
          integration: lambda-proxy
  errorsGet:
    handler: src/handlers/errors/get.get
    events:
      - http:
          path: projects/{project}/errors/{message}
          method: get
          cors: true
          integration: lambda-proxy
  errorsPatch:
    handler: src/handlers/errors/patch.patch
    events:
      - http:
          path: projects/{project}/errors/{message}
          method: patch
          cors: true
          integration: lambda-proxy
  errorsDelete:
    handler: src/handlers/errors/delete.delete
    timeout: 30
    events:
      - http:
          path: projects/{project}/errors/{message}
          method: delete
          cors: true
          integration: lambda-proxy
  occurrencesList:
    handler: src/handlers/occurrences/get.list
    events:
      - http:
          path: projects/{project}/errors/{message}/occurrences
          method: get
          cors: true
          integration: lambda-proxy
  occurrencesGet:
    handler: src/handlers/occurrences/get.get
    events:
      - http:
          path: projects/{project}/errors/{message}/occurrences/{reversedUnixtime}
          method: get
          cors: true
          integration: lambda-proxy
  callNotifications:
    handler: src/handlers/notifications.call
    name: faultline-${self:provider.stage}-callNotifications
    timeout: 30
  encrypt:
    handler: src/handlers/util.encrypt
    events:
      - http:
          path: encrypt
          method: post
          integration: lambda-proxy

resources:
  Resources: ${file(src/lib/resources.js):resources}
